name: ssh_service_down
description: Start SSH service when it stops
pack: mypack
enabled: true
trigger:
  type: "core.st2.generic"
  parameters:
    trigger_service: "ssh"
    trigger_status: "down"
action:
  ref: mypack.start_ssh
  parameters: {}
